spring.application.name=module3
#spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.url=jdbc:h2:file:./h2-database/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA ? automatyczne tworzenie tabel
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
# Opcjonalnie ? poka? sql w konsoli (bardzo pomocne przy debugowaniu)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Konsola H2 w przegl?darce (http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.security.user.password=abc123


spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
# Producent ? wy??cz type headers (bezpieczne i rozwi?zuje 90% problemów)

# Opcjonalnie: typowy setup konsumenta
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.module3.dto.ReportRequestedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.group-id=test-grupa-statyczna
spring.kafka.consumer.auto-offset-reset=earliest
#logging.level.org.springframework.boot.autoconfigure=DEBUG
#logging.level.org.springframework.kafka=DEBUG
#logging.level.org.springframework.boot.autoconfigure.condition=TRACE